<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="SAM" failures="2" tests="2" name="Test(failed)" time="0.217" errors="0" timestamp="2023-03-16T22:15:06 IST">
  <testcase classname="RetryLogic.TestcaseseExa" name="TestCase2" time="0.055">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RetryLogic.TestcaseseExa.TestCase2(TestcaseseExa.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TestCase2 -->
  <testcase classname="RetryLogic.TestcaseseExa" name="testCase1" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RetryLogic.TestcaseseExa.testCase1(TestcaseseExa.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testCase1 -->
  <testcase classname="RetryLogic.TestcaseseExa" name="TestCase3" time="0.0">
    <ignored/>
  </testcase> <!-- TestCase3 -->
</testsuite> <!-- Test(failed) -->
